# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e72e93c26299a397ab3a09fd65e8746169b39cdeefe2576dd6fc13eb797a6349aea80c03ed63977cf72f6e59c687cf5a694f543713085a937f2a7c670fbb0f11

test:
  secret_key_base: ff24760e05514af314adac956da1a61d3c5a366421880b601b56ab2af73cb29fd45618213f3db35f77e3f511f4a3a905184e09cab2fd4a0445f927dad11f24a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
